apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-prediction-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-prediction-app
  template:
    metadata:
      labels:
        app: diabetes-prediction-app
    spec:
      containers:
      - name: diabetes-prediction-app
        image: diabetes_prediction_app:0.0.12
        ports:
        - containerPort: 5000
