apiVersion: v1
kind: Service
metadata:
  name: diabetes-prediction-app-service
spec:
  selector:
    app: diabetes-prediction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
